services:

  postgres:
    image: postgres:17-alpine
    container_name: billing-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: billing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d billing_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    networks:
      - billing-network

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: billing-rabbitmq

    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    ports:
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

    networks:
      - billing-network

  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: billing-api:latest
    container_name: billing-api

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}

      NODE_ENV: production

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://18.221.97.172:3000/api/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - billing-network

volumes:
  postgres_data:
    driver: local

  rabbitmq_data:
    driver: local

networks:
  billing-network:
    driver: bridge